### ISSUE TITLE
Error when moving collapsed threaded messages as a whole

### ISSUE THREAD

**Issue by TmtStss** [kewisch/quickmove-extension#163]
This issue has arisen since the new QuickMove update (TB128). Moving a single message works as usual. Moving a collapsed thread of messages used to work identically, moving all the messages in the thread to the desired folder. Since the update, QuickMove gets stuck (little wheel symbol keeps spinning) when attempting to do that.

**Comment by kewisch** [comment]
This is fixed in QFM 2.9.2 which is pending review. Thanks for reporting!

**Comment by TmtStss** [comment]
@kewisch: thank you for your proactivity in fixing these issues, much appreciated! The issue with moving threads is however only partially solved in QFM 2.9.2.
- What is solved: selecting multiple messages in a non-collapsed thread and moving them with QFM.
- What is not solved/still a bug: moving a collapsed thread as whole: it only moves the first message of the thread.
I hope it's clear, otherwise I can try to provide more detailed explanations/screenshots.

**Comment by gypsychk** [comment]
@kewisch I'm experiencing the same thing as @TmtStss .
